import { Router } from 'express';
import fs from 'fs';
import path from 'path';
import os from 'os';

const router = Router();

/**
 * GET /api/music
 *
 * Streams a calm, slow, loopable background-music MP3 generated by ElevenLabs'
 * sound-generation API. Generated ONCE, then cached in memory + on disk so the
 * same bytes are served forever (the browser loops them seamlessly).
 *
 * If ELEVENLABS_API_KEY is not configured — or generation fails — this responds
 * 503 so the frontend silently falls back to its built-in synth ambient engine.
 * That keeps "calm background music" working everywhere without ever breaking.
 */
const PROMPT = process.env.ELEVENLABS_MUSIC_PROMPT
  || 'Calm, slow, gentle lo-fi ambient background music for studying and focus. '
   + 'Soft mellow piano and warm pads, light vinyl warmth, relaxing and unobtrusive, '
   + 'seamless loop, no vocals, minimal or no drums.';
const DURATION_S = Number(process.env.ELEVENLABS_MUSIC_SECONDS || 22); // sound-gen max ~22s
const CACHE_FILE = path.join(os.tmpdir(), 'lh-bg-music.mp3');

let memBuf = null;

async function generateMusic(apiKey) {
  const r = await fetch('https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_128', {
    method: 'POST',
    headers: { 'xi-api-key': apiKey, 'Content-Type': 'application/json', 'Accept': 'audio/mpeg' },
    body: JSON.stringify({
      text: PROMPT,
      duration_seconds: Math.min(22, Math.max(4, DURATION_S)),
      loop: true,
      prompt_influence: 0.3,
    }),
  });
  if (!r.ok) {
    const body = await r.text().catch(() => '');
    throw new Error(`elevenlabs sound-generation ${r.status}: ${body.slice(0, 160)}`);
  }
  const buf = Buffer.from(await r.arrayBuffer());
  if (buf.length < 500) throw new Error(`music returned ${buf.length} bytes`);
  return buf;
}

function sendMp3(res, buf, source) {
  res.set('Content-Type', 'audio/mpeg');
  res.set('Cache-Control', 'public, max-age=604800, immutable');
  res.set('Accept-Ranges', 'bytes');
  res.set('X-Music-Source', source);
  res.send(buf);
}

router.get('/', async (_req, res) => {
  try {
    if (memBuf) { sendMp3(res, memBuf, 'memory'); return; }
    try {
      const b = fs.readFileSync(CACHE_FILE);
      if (b && b.length > 500) { memBuf = b; sendMp3(res, b, 'disk'); return; }
    } catch { /* no disk cache yet */ }

    const apiKey = process.env.ELEVENLABS_API_KEY;
    if (!apiKey) { res.status(503).json({ error: 'music unavailable (no ELEVENLABS_API_KEY)' }); return; }

    const buf = await generateMusic(apiKey);
    memBuf = buf;
    try { fs.writeFileSync(CACHE_FILE, buf); } catch { /* tmp not writable — memory cache is enough */ }
    sendMp3(res, buf, 'elevenlabs');
  } catch (err) {
    // Never 500 — let the client fall back to the synth ambient engine.
    // eslint-disable-next-line no-console
    console.warn('[music] generation failed:', err?.message);
    res.status(503).json({ error: 'music generation failed' });
  }
});

export default router;
